### ISSUE TITLE
这个多线程有问题吧

### ISSUE THREAD

**Issue by geekmc** [Jumbo-WJB/notes#1]

**Comment by Jumbo-WJB** [comment]
哪里出错了？

**Comment by geekmc** [comment]
join和star 能这么写嘛？




| |
马帅
邮箱：craymc@163.com
|

签名由 网易邮箱大师 定制

在2018年02月26日 17:22，Jumbo 写道：

哪里出错了？

**Comment by geekmc** [comment]
join和start能这样写吗？

**Comment by geekmc** [comment]
你测试一下速度有提高没有

**Comment by Jumbo-WJB** [comment]
多线程不是很熟练，能否指教下怎么改？

**Comment by Jumbo-WJB** [comment]
感谢，已修改。
